(function(g){var window=this;var T5=function(a){g.vD.call(this,{C:"div",G:"ytp-miniplayer-ui"});this.player=a;this.H=!1;this.F=this.u=this.l=void 0;this.K(a,"minimized",this.XJ);this.K(a,"onStateChange",this.ZM)},U5=function(a){g.oL.call(this,a);
    this.g=new T5(this.player);this.g.hide();g.ZK(this.player,this.g.element,4);a.app.F.g&&(this.load(),g.I(a.getRootNode(),"ytp-player-minimized",!0))};
    g.t(T5,g.vD);g.h=T5.prototype;
    g.h.show=function(){this.l=new g.Bo(this.fG,null,this);this.l.start();if(!this.H){this.B=new g.LW(this.player,this);g.B(this,this.B);g.ZK(this.player,this.B.element,4);this.B.A=.6;this.P=new g.OV(this.player);g.B(this,this.P);this.A=new g.V({C:"div",G:"ytp-miniplayer-scrim"});g.B(this,this.A);this.A.g(this.element);this.K(this.A.element,"click",this.pz);var a=new g.V({C:"button",W:["ytp-miniplayer-close-button","ytp-button"],L:{"aria-label":"Close"},J:[g.dQ()]});g.B(this,a);a.g(this.A.element);this.K(a.element,
    "click",this.Mx);this.o=new g.V({C:"div",G:"ytp-miniplayer-controls"});g.B(this,this.o);this.o.g(this.A.element);this.K(this.o.element,"click",this.pz);var b=new g.V({C:"div",G:"ytp-miniplayer-button-container"});g.B(this,b);b.g(this.o.element);a=new g.V({C:"div",G:"ytp-miniplayer-play-button-container"});g.B(this,a);a.g(this.o.element);var c=new g.V({C:"div",G:"ytp-miniplayer-button-container"});g.B(this,c);c.g(this.o.element);this.M=new g.PT(this.player,this,!1);g.B(this,this.M);this.M.g(b.element);
    b=new g.MT(this.player,this);g.B(this,b);b.g(a.element);this.I=new g.PT(this.player,this,!0);g.B(this,this.I);this.I.g(c.element);this.F=new g.iV(this.player,this);g.B(this,this.F);this.F.g(this.A.element);this.u=new g.VT(this.player,this);g.B(this,this.u);g.ZK(this.player,this.u.element,4);this.D=new g.V({C:"div",G:"ytp-miniplayer-buttons"});g.B(this,this.D);g.ZK(this.player,this.D.element,4);a=new g.V({C:"button",W:["ytp-miniplayer-close-button","ytp-button"],L:{"aria-label":"Close"},J:[g.dQ()]});
    g.B(this,a);a.g(this.D.element);this.K(a.element,"click",this.Mx);a=new g.V({C:"button",W:["ytp-miniplayer-replay-button","ytp-button"],L:{"aria-label":"Close"},J:[g.rQ()]});g.B(this,a);a.g(this.D.element);this.K(a.element,"click",this.SK);this.K(this.player,"presentingplayerstatechange",this.gG);this.K(this.player,"appresize",this.Va);this.K(this.player,"fullscreentoggled",this.Va);this.Va();this.H=!0}0!=this.player.getPlayerState()&&g.vD.prototype.show.call(this);this.u.show();this.player.unloadModule("annotations_module")};
    g.h.hide=function(){this.l&&(this.l.dispose(),this.l=void 0);g.vD.prototype.hide.call(this);this.player.app.F.g||(this.H&&this.u.hide(),this.player.loadModule("annotations_module"))};
    g.h.U=function(){this.l&&(this.l.dispose(),this.l=void 0);g.vD.prototype.U.call(this)};
    g.h.Mx=function(){this.player.stopVideo();this.player.la("onCloseMiniplayer")};
    g.h.SK=function(){this.player.playVideo()};
    g.h.pz=function(a){if(a.target==this.A.element||a.target==this.o.element)g.O(g.W(this.player).experiments,"kevlar_miniplayer_scrim_pause")?2==this.player.getPlayerState()?this.player.playVideo():this.player.pauseVideo():this.player.la("onExpandMiniplayer")};
    g.h.XJ=function(){g.I(this.player.getRootNode(),"ytp-player-minimized",this.player.app.F.g)};
    g.h.fG=function(){this.u.Nc();this.F.Nc();this.l&&this.l.start()};
    g.h.gG=function(a){g.T(a.state,32)&&this.B.hide()};
    g.h.Va=function(){var a=this.u,b=g.LK(this.player).getPlayerSize().width;a.Ba=0;a.A=b;a.D=!1;g.XT(a)};
    g.h.ZM=function(a){this.player.app.F.g&&(0==a?this.hide():this.show())};
    g.h.ab=function(){return this.B};
    g.h.ec=function(){return!1};
    g.h.wg=function(){return!1};
    g.h.ji=function(){return!1};
    g.h.Rs=function(){};
    g.h.Vg=function(){};
    g.h.xj=function(){};
    g.h.An=function(){return null};
    g.h.vr=function(){return new g.lh(0,0,0,0)};
    g.h.handleGlobalKeyDown=function(){return!1};
    g.h.handleGlobalKeyUp=function(){return!1};
    g.h.Ik=function(a,b,c,d,e){var f=0,k=d=0,l=g.Rh(a);if(b){c=g.po(b,"ytp-prev-button")||g.po(b,"ytp-next-button");var m=g.po(b,"ytp-play-button");c?f=k=12:m&&(b=g.Oh(b,this.element),k=b.x,f=b.y-12)}else k=c-l.width/2,d=25+(e||0);b=g.LK(this.player).getPlayerSize().width;e=f+(e||0);k=g.nd(k,0,b-l.width);e?(a.style.top=e+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=k+"px"};
    g.h.showControls=function(){};
    g.h.wr=function(){};
    g.h.Sh=function(){};g.t(U5,g.oL);U5.prototype.init=function(){};
    U5.prototype.load=function(){this.player.hideControls();this.g.show()};
    U5.prototype.unload=function(){this.player.showControls();this.g.hide()};g.KV.miniplayer=U5;})(_yt_player);